### ISSUE TITLE
Restrict behavior to Local volumes only

### ISSUE THREAD

**Issue by lindseydiloreto** [putyourlightson/craft-untransform#1]
We've recently had a conflict with the S3 plugin (using Cloudfront). Untransform was applying the `baseUrlPrefix` value to our Cloudfront URL, which obviously doesn't work:

```
https://clientsite.com/https://cloudfronturl...
```

Would it be possible to restrict Untransform's behavior to apply to only Local volumes? It's probably safe to assume that any non-local volume would not need this feature.

Related... should Untransform recognize that it's already working with a full URL, and bypass the prefix addition?

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-untransform/commit/59719fcd148b9c5607351346f980932352dee511 for the next release.

**Comment by lindseydiloreto** [comment]
Amazing, thanks @bencroker! 🍺

**Comment by bencroker** [comment]
Released in version 1.0.2.
