### ISSUE TITLE
Enable for local/staging but disable for Production

### ISSUE THREAD

**Issue by RyanRoberts** [putyourlightson/craft-untransform#2]
Hey there, maybe I've misunderstood how the plugin should work but I was expecting it to only display a placeholder image if the correct image was missing. However, it appears to be an all or nothing situation.

I have a site with a huge amount of high res images (I don't want to have to download) and installed the plugin thinking it would solve the problem… that it does in fact solve, but locally. Anyway when I pushed some updates to production the site had all its images replaced with the placeholder 🤦‍♂️🫠 …oops, I had to quickly disable Untransform.

Maybe there's a way to enable the plugin depending on environment?

Thanks!

**Comment by bencroker** [comment]
Sorry, this issue went under my radar somehow.

You can either disable the plugin in non-development environments or use [config settings](https://github.com/putyourlightson/craft-untransform/blob/develop/src/config.php), which are multi-environment aware.

**Comment by RyanRoberts** [comment]
Thanks!
